
services:

  servicio_vacunas:
    build: ../control-vacunas-servicio
    container_name: servicio_vacunas
    ports:
      - "3000:3000"
  
  cliente_vacunas:
    build: ../control-vacunas-cliente
    container_name: control-vacunas-cliente
    ports:
      - "5173:80"
    depends_on:
      - servicio_vacunas